<?php
$students = [
  'Cha Eun Woo' => [
		'grade' => 'A+',
		'id' => 271731 ],
	'Moon Bin' => [
		'grade' => 'A', 
		'id' => 815211]
	];
$sotre = [
	'tissue' => '1',
	'bottle' => '4', 
	'cup' => '3', 
	'basket' => '2'];
$lunches = [ 
	'Monday' => [
		'cost' => 4000,
		'entree' => 'Beef Shu-Mai',
		'side' => 'Salty Fried Cake',
		'drink' => 'Black Tea' ],
	'Tuesday' => [ 
		'cost' => 4500,
		'entree' => 'Clear-steamed Fish',
		'side' => 'Turnip Cake',
		'drink' => 'Bubble Tea' ],
	'Wednesday' => [ 
		'cost' => 3000,
		'entree' => 'Braised Sea Cucumber',
		'side' => 'Turnip Cake',
		'drink' => 'Green Tea' ],
	'Thursday' => [ 
		'cost' => 3500,
		'entree' => 'Stir-fried Two Winters',
		'side' => 'Egg Puff',
		'drink' => 'Black Tea' ],
	'Friday' => [
		'cost' => 4500,
		'entree' => 'Stewed Pork with Taro',
		'side' => 'Duck Feet',
		'drink' => 'Jasmine Tea' ]
	];
$family_astro = [ 'Cha Eun Woo', 'Moon Bin', 'Jin Jin', 'Saha', 'MJ', 'Rocky'];
$family_astro = [
	'Cha Eun Woo' => [
		'age' => 22,
		'relation' => 'brother' ],
	'Moon Bin' => [
		'age' => 22,
		'relation' => 'brother' ],
	'Jin Jin' => [
		'age' => 22,
		'relation' => 'brother' ],
	'Saha' => [
		'age' => 22,
		'relation' => 'brother' ],
	'MJ' => [
		'age' => 22,
		'relation' => 'brother' ],
	'Rocky' => [
		'age' => 22,
		'relation' => 'brother' ]
];
?>
